DROP TABLE IF EXISTS Ratings;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE Ratings (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    rating INT NOT NULL CHECK (rating BETWEEN  1 AND 5),
    userID INT NOT NULL,
    FOREIGN KEY (userID) REFERENCES Users(id)
);